# -*- coding: utf-8 -*-
"""Task2(Supervised).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZN13WFjut3MZ6biu2Nj00IujEJPVVym"""

"""# To Explore Supervised Machine Learning"""

"""## Importing libraries"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Import dataset"""

dataset= pd.read_csv('student_scores - student_scores.csv')
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:,1].values

"""## Splitting the dataset as training and test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)

y_test

"""## Training the linear regression model on training set"""

from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train,y_train)

"""## Predicting test set results"""

y_pred= regressor.predict(X_test)

y_pred

"""## Visualising training set results"""

plt.scatter(X_train,y_train,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('Study hours vs Marks(Training set)')
plt.xlabel('Study hours')
plt.ylabel('Marks')
plt.show()

"""## Visualising test set results"""

plt.scatter(X_test,y_test,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('Study hours vs Marks(Test set)')
plt.xlabel('Study hours')
plt.ylabel('Marks')
plt.show()

"""## Evaluation"""

from sklearn import metrics  
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test, y_pred))

"""## Predicting result for given study hour"""

regressor.predict([[9.25]])
